### ISSUE TITLE
Checks for cluster commands in sos_comands/cluster

### ISSUE THREAD

**Issue by iranzo** [OndrejHome/sd-cluster-check#1]
Hi,
I was trying to check sd-cluster-check in order to integrate with citellus via https://github.com/zerodayz/citellus/issues/56 but the first issue I found while checking is that it looks for sos_commands/cluster only and it doesn't search for sos_commands/pacemaker where sometimes data is stored.

~~~
== sd-cluster-check v0.2 ==
Searching for sosreports in given path(s)
path: ../sosreport-controller-0-20171212110438/
found ../sosreport-controller-0-20171212110438
[i] 1 sosreport(s) found, processing them now
[w] sos_commands/cluster not present in ../sosreport-controller-0-20171212110438
============ detected 1 cluster(s)
==== tripleo_cluster ( pacemaker )
#  heartbeat IP     sos  crm  node name           
1  172.17.1.14      yes  yes  controller-0   
2  172.17.1.16      NO   NO   controller-1   
3  172.17.1.18      NO   NO   controller-2   
~~~

My idea was to integrate it along the cluster scripts we already have at: https://github.com/zerodayz/citellus/tree/master/citellusclient/plugins/core/pacemaker

Regards,
Pablo

**Comment by OndrejHome** [comment]
Hi Pablo,
thank you for checking this. It was quite a time I made changes here and in 'develop' branch I had commit that detects the `sos_commands/cluster` as well as `sos_commands/pacemaker` variant. I have added one additional change I bumped into and merged all of that into master. Could you please let me know if you can detect the sosreports now properly? If not would it be possible to somehow share the sosreports so I can check them?

**Comment by iranzo** [comment]
I've a sample one in 01991880 from a OSP12 controller using containers

**Comment by OndrejHome** [comment]
Checking the sample with previous version v0.2 I see that script reports `sos_commands/cluster` missing and shows `no` for crm_report of node id 1.

~~~
== sd-cluster-check v0.2 ==
Searching for sosreports in given path(s)
path: sosreport-controller-0-20171212110438/
found sosreport-controller-0-20171212110438
[i] 1 sosreport(s) found, processing them now
[w] sos_commands/cluster not present in sosreport-controller-0-20171212110438
============ detected 1 cluster(s)
==== tripleo_cluster ( pacemaker )
#  heartbeat IP     sos  crm  node name           
1  172.17.1.14      yes  NO   controller-0   
2  172.17.1.16      NO   NO   controller-1   
3  172.17.1.18      NO   NO   controller-2   
~~~

Now in the new version v0.3 it detects the crm_report and also doesn't complain about `sos_commands/cluster` missing. This looks to me like a proper detection now.

~~~
== sd-cluster-check v0.3 ==
Searching for sosreports in given path(s)
path: sosreport-controller-0-20171212110438/
found sosreport-controller-0-20171212110438
[i] 1 sosreport(s) found, processing them now
============ detected 1 cluster(s)
==== tripleo_cluster ( pacemaker )
#  heartbeat IP     sos  crm  node name           
1  172.17.1.14      yes  yes  controller-0   
2  172.17.1.16      NO   NO   controller-1   
3  172.17.1.18      NO   NO   controller-2 
~~~
Hope this is OK for your use now.

As for integrating this into citellus feel free go ahead. At moment I'm using this script as detection tool to determine which sosreports for cluster I have. Also in version 0.3 there is now option '-v' that will print the paths for sosreports which is useful when there are many of them or if you have multiple sosreports from same node (example below).

~~~
$ ./sd-cluster-check-v0.3 -v sosreport-controller-0-20171212110438/
== sd-cluster-check v0.3 ==
Searching for sosreports in given path(s)
path: sosreport-controller-0-20171212110438/
found sosreport-controller-0-20171212110438
[i] 1 sosreport(s) found, processing them now
============ detected 1 cluster(s)
==== tripleo_cluster ( pacemaker )
#  heartbeat IP     sos  crm  node name           
1  172.17.1.14      yes  yes  controller-0   
   - Tue Dec 12 11:05:25 UTC 2017 - sosreport-controller-0-20171212110438
2  172.17.1.16      NO   NO   controller-1   
[ no sosreports for this node]
3  172.17.1.18      NO   NO   controller-2   
[ no sosreports for this node]
~~~

Closing this issue now as it seems that new version is detecting the pacemaker directory properly. In case this doesn't work for some other sosreport feel free to re-open this issue or create a new one.
